### ISSUE TITLE
makefile is not finding scintilla headers

### ISSUE THREAD

**Issue by DeweyTaylor** [waddlesplash/Heidi#6]
expects them to be in /boot/system/develop/headers but they actually reside in /boot/system/develop/headers/scintilla
also use of  `#include "file"` for system headers (Scintilla.h) instead of `#include <file>`

**Comment by waddlesplash** [comment]
Fixed in 4f17b1f9daab04f2aad679a86e640ad870c32f2d, but you need to use the newest Scintilla recipe (not the package in the depot, it's busted), and the GCC5 variant at that too.
